"""change update_user_id column in post

Revision ID: 46d7d6ee6a0a
Revises: 00f7ccb63169
Create Date: 2026-01-26 21:11:59.042993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46d7d6ee6a0a'
down_revision = '00f7ccb63169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('updated_user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('updated_user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
